//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Aggregation Event captures an event that applies to objects that
 * 			have a physical association with one another.
 *            	
 * 
 * <p>Java class for AggregationEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggregationEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:epcglobal:epcis:xsd:1}EPCISEventType">
 *       &lt;sequence>
 *         &lt;element name="parentID" type="{urn:epcglobal:epcis:xsd:1}ParentIDType" minOccurs="0"/>
 *         &lt;element name="childEPCs" type="{urn:epcglobal:epcis:xsd:1}EPCListType"/>
 *         &lt;element name="action" type="{urn:epcglobal:epcis:xsd:1}ActionType"/>
 *         &lt;element name="bizStep" type="{urn:epcglobal:epcis:xsd:1}BusinessStepIDType" minOccurs="0"/>
 *         &lt;element name="disposition" type="{urn:epcglobal:epcis:xsd:1}DispositionIDType" minOccurs="0"/>
 *         &lt;element name="readPoint" type="{urn:epcglobal:epcis:xsd:1}ReadPointType" minOccurs="0"/>
 *         &lt;element name="bizLocation" type="{urn:epcglobal:epcis:xsd:1}BusinessLocationType" minOccurs="0"/>
 *         &lt;element name="bizTransactionList" type="{urn:epcglobal:epcis:xsd:1}BusinessTransactionListType" minOccurs="0"/>
 *         &lt;element name="extension" type="{urn:epcglobal:epcis:xsd:1}AggregationEventExtensionType" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}eventID" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}declaringParty" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}retractionFlag" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}replacementEventID" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}retractionReason" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregationEventType", propOrder = {
    "parentID",
    "childEPCs",
    "action",
    "bizStep",
    "disposition",
    "readPoint",
    "bizLocation",
    "bizTransactionList",
    "extension",
    "eventID",
    "declaringParty",
    "retractionFlag",
    "replacementEventID",
    "retractionReason"
})
public class AggregationEventType
    extends EPCISEventType
{

    protected String parentID;
    @XmlElement(required = true)
    protected EPCListType childEPCs;
    @XmlElement(required = true)
    protected ActionType action;
    protected BusinessStepIDType bizStep;
    protected DispositionIDType disposition;
    protected ReadPointType readPoint;
    protected BusinessLocationType bizLocation;
    protected BusinessTransactionListType bizTransactionList;
    protected AggregationEventExtensionType extension;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected String eventID;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected String declaringParty;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected Boolean retractionFlag;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected String replacementEventID;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected String retractionReason;

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the childEPCs property.
     * 
     * @return
     *     possible object is
     *     {@link EPCListType }
     *     
     */
    public EPCListType getChildEPCs() {
        return childEPCs;
    }

    /**
     * Sets the value of the childEPCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPCListType }
     *     
     */
    public void setChildEPCs(EPCListType value) {
        this.childEPCs = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the bizStep property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessStepIDType }
     *     
     */
    public BusinessStepIDType getBizStep() {
        return bizStep;
    }

    /**
     * Sets the value of the bizStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessStepIDType }
     *     
     */
    public void setBizStep(BusinessStepIDType value) {
        this.bizStep = value;
    }

    /**
     * Gets the value of the disposition property.
     * 
     * @return
     *     possible object is
     *     {@link DispositionIDType }
     *     
     */
    public DispositionIDType getDisposition() {
        return disposition;
    }

    /**
     * Sets the value of the disposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispositionIDType }
     *     
     */
    public void setDisposition(DispositionIDType value) {
        this.disposition = value;
    }

    /**
     * Gets the value of the readPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointType }
     *     
     */
    public ReadPointType getReadPoint() {
        return readPoint;
    }

    /**
     * Sets the value of the readPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointType }
     *     
     */
    public void setReadPoint(ReadPointType value) {
        this.readPoint = value;
    }

    /**
     * Gets the value of the bizLocation property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessLocationType }
     *     
     */
    public BusinessLocationType getBizLocation() {
        return bizLocation;
    }

    /**
     * Sets the value of the bizLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessLocationType }
     *     
     */
    public void setBizLocation(BusinessLocationType value) {
        this.bizLocation = value;
    }

    /**
     * Gets the value of the bizTransactionList property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessTransactionListType }
     *     
     */
    public BusinessTransactionListType getBizTransactionList() {
        return bizTransactionList;
    }

    /**
     * Sets the value of the bizTransactionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessTransactionListType }
     *     
     */
    public void setBizTransactionList(BusinessTransactionListType value) {
        this.bizTransactionList = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link AggregationEventExtensionType }
     *     
     */
    public AggregationEventExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregationEventExtensionType }
     *     
     */
    public void setExtension(AggregationEventExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventID(String value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the declaringParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclaringParty() {
        return declaringParty;
    }

    /**
     * Sets the value of the declaringParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclaringParty(String value) {
        this.declaringParty = value;
    }

    /**
     * Gets the value of the retractionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetractionFlag() {
        return retractionFlag;
    }

    /**
     * Sets the value of the retractionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetractionFlag(Boolean value) {
        this.retractionFlag = value;
    }

    /**
     * Gets the value of the replacementEventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacementEventID() {
        return replacementEventID;
    }

    /**
     * Sets the value of the replacementEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacementEventID(String value) {
        this.replacementEventID = value;
    }

    /**
     * Gets the value of the retractionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetractionReason() {
        return retractionReason;
    }

    /**
     * Sets the value of the retractionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetractionReason(String value) {
        this.retractionReason = value;
    }

}
