//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessStepIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusinessStepIDType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:commissioning"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:packing"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:unpacking"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:shipping"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:receiving"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:destroying"/>
 *     &lt;enumeration value="urn:epcglobal:cbv:bizstep:inspecting"/>
 *     &lt;enumeration value="http://epcis.gs1br.org/hc/bizstep/dispensing"/>
 *     &lt;enumeration value="http://epcis.gs1br.org/hc/bizstep/importing"/>
 *     &lt;enumeration value="http://epcis.gs1br.org/hc/bizstep/recovering"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusinessStepIDType")
@XmlEnum
public enum BusinessStepIDType {

    @XmlEnumValue("urn:epcglobal:cbv:bizstep:commissioning")
    URN_EPCGLOBAL_CBV_BIZSTEP_COMMISSIONING("urn:epcglobal:cbv:bizstep:commissioning"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:packing")
    URN_EPCGLOBAL_CBV_BIZSTEP_PACKING("urn:epcglobal:cbv:bizstep:packing"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:unpacking")
    URN_EPCGLOBAL_CBV_BIZSTEP_UNPACKING("urn:epcglobal:cbv:bizstep:unpacking"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:shipping")
    URN_EPCGLOBAL_CBV_BIZSTEP_SHIPPING("urn:epcglobal:cbv:bizstep:shipping"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:receiving")
    URN_EPCGLOBAL_CBV_BIZSTEP_RECEIVING("urn:epcglobal:cbv:bizstep:receiving"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:destroying")
    URN_EPCGLOBAL_CBV_BIZSTEP_DESTROYING("urn:epcglobal:cbv:bizstep:destroying"),
    @XmlEnumValue("urn:epcglobal:cbv:bizstep:inspecting")
    URN_EPCGLOBAL_CBV_BIZSTEP_INSPECTING("urn:epcglobal:cbv:bizstep:inspecting"),
    @XmlEnumValue("http://epcis.gs1br.org/hc/bizstep/dispensing")
    HTTP_EPCIS_GS_1_BR_ORG_HC_BIZSTEP_DISPENSING("http://epcis.gs1br.org/hc/bizstep/dispensing"),
    @XmlEnumValue("http://epcis.gs1br.org/hc/bizstep/importing")
    HTTP_EPCIS_GS_1_BR_ORG_HC_BIZSTEP_IMPORTING("http://epcis.gs1br.org/hc/bizstep/importing"),
    @XmlEnumValue("http://epcis.gs1br.org/hc/bizstep/recovering")
    HTTP_EPCIS_GS_1_BR_ORG_HC_BIZSTEP_RECOVERING("http://epcis.gs1br.org/hc/bizstep/recovering");
    private final String value;

    BusinessStepIDType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusinessStepIDType fromValue(String v) {
        for (BusinessStepIDType c: BusinessStepIDType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
