//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for BusinessTransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessTransactionType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:epcglobal:epcis:xsd:1>BusinessTransactionIDType">
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:epcglobal:epcis:xsd:1}BusinessTransactionTypeIDType">
 *             &lt;enumeration value="http://epcis.gs1br.org/hc/btt/delivery"/>
 *             &lt;enumeration value="http://epcis.gs1br.org/hc/btt/notafiscal"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:inv"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:po"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:bol"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:rma"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:desadv"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:recadv"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:salesorder"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:packslip"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:destruction"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:transfer"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:other"/>
 *             &lt;enumeration value="urn:epcglobal:cbv:btt:prodorder"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessTransactionType", propOrder = {
    "value"
})
public class BusinessTransactionType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
