//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilesetPaginationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilesetPaginationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}filesetIdentifier"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}instance"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}total"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilesetPaginationType", namespace = "http://epcis.gs1br.org/hc/ns", propOrder = {
    "filesetIdentifier",
    "instance",
    "total"
})
public class FilesetPaginationType {

    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns", required = true)
    protected BigInteger filesetIdentifier;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns", required = true)
    protected BigInteger instance;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns", required = true)
    protected BigInteger total;

    /**
     * Gets the value of the filesetIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFilesetIdentifier() {
        return filesetIdentifier;
    }

    /**
     * Sets the value of the filesetIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFilesetIdentifier(BigInteger value) {
        this.filesetIdentifier = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstance(BigInteger value) {
        this.instance = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotal(BigInteger value) {
        this.total = value;
    }

}
