//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ILMDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ILMDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extension" type="{urn:epcglobal:epcis:xsd:1}ILMDExtensionType" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}ANVISARegistrationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}expirationDate" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}manufacturingDate" minOccurs="0"/>
 *         &lt;element ref="{http://epcis.gs1br.org/hc/ns}packagingLevel" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ILMDType", propOrder = {
    "extension",
    "anvisaRegistrationNumber",
    "expirationDate",
    "manufacturingDate",
    "packagingLevel"
})
public class ILMDType {

    protected ILMDExtensionType extension;
    @XmlElement(name = "ANVISARegistrationNumber", namespace = "http://epcis.gs1br.org/hc/ns")
    protected String anvisaRegistrationNumber;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar manufacturingDate;
    @XmlElement(namespace = "http://epcis.gs1br.org/hc/ns")
    protected PackagingLevelType packagingLevel;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ILMDExtensionType }
     *     
     */
    public ILMDExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ILMDExtensionType }
     *     
     */
    public void setExtension(ILMDExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the anvisaRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANVISARegistrationNumber() {
        return anvisaRegistrationNumber;
    }

    /**
     * Sets the value of the anvisaRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANVISARegistrationNumber(String value) {
        this.anvisaRegistrationNumber = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the manufacturingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getManufacturingDate() {
        return manufacturingDate;
    }

    /**
     * Sets the value of the manufacturingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setManufacturingDate(XMLGregorianCalendar value) {
        this.manufacturingDate = value;
    }

    /**
     * Gets the value of the packagingLevel property.
     * 
     * @return
     *     possible object is
     *     {@link PackagingLevelType }
     *     
     */
    public PackagingLevelType getPackagingLevel() {
        return packagingLevel;
    }

    /**
     * Sets the value of the packagingLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagingLevelType }
     *     
     */
    public void setPackagingLevel(PackagingLevelType value) {
        this.packagingLevel = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
