//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MasterDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:epcglobal:epcis-masterdata:xsd:1}VocabularyList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterDataType", namespace = "http://epcis.gs1br.org/hc/ns", propOrder = {
    "vocabularyList"
})
public class MasterDataType {

    @XmlElement(name = "VocabularyList", namespace = "urn:epcglobal:epcis-masterdata:xsd:1")
    protected VocabularyListType vocabularyList;

    /**
     * Gets the value of the vocabularyList property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularyListType }
     *     
     */
    public VocabularyListType getVocabularyList() {
        return vocabularyList;
    }

    /**
     * Sets the value of the vocabularyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularyListType }
     *     
     */
    public void setVocabularyList(VocabularyListType value) {
        this.vocabularyList = value;
    }

}
