//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MovementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MovementType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PURCHASE_SALE"/>
 *     &lt;enumeration value="TRANSFERENCE"/>
 *     &lt;enumeration value="RETURN"/>
 *     &lt;enumeration value="COLLECTION"/>
 *     &lt;enumeration value="FREE_SAMPLE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MovementType", namespace = "http://epcis.gs1br.org/hc/ns")
@XmlEnum
public enum MovementType {

    PURCHASE_SALE,
    TRANSFERENCE,
    RETURN,
    COLLECTION,
    FREE_SAMPLE;

    public String value() {
        return name();
    }

    public static MovementType fromValue(String v) {
        return valueOf(v);
    }

}
