//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 10:08:09 AM BRT 
//


package br.org.usp.models;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.org.usp.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VocabularyList_QNAME = new QName("urn:epcglobal:epcis-masterdata:xsd:1", "VocabularyList");
    private final static QName _CarrierParty_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "carrierParty");
    private final static QName _Instance_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "instance");
    private final static QName _FilesetIdentifier_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "filesetIdentifier");
    private final static QName _EPCISDocument_QNAME = new QName("urn:epcglobal:epcis:xsd:1", "EPCISDocument");
    private final static QName _ManufacturingDate_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "manufacturingDate");
    private final static QName _ExpectedNumUnits_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "expectedNumUnits");
    private final static QName _RetractionFlag_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "retractionFlag");
    private final static QName _EventID_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "eventID");
    private final static QName _StandardBusinessDocumentHeader_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocumentHeader");
    private final static QName _StandardBusinessDocument_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocument");
    private final static QName _RetractionReason_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "retractionReason");
    private final static QName _NatureOfMovement_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "natureOfMovement");
    private final static QName _LotNumber_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "lotNumber");
    private final static QName _DeclaringParty_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "declaringParty");
    private final static QName _MasterData_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "masterData");
    private final static QName _ExpectedNumUnitUOM_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "expectedNumUnitUOM");
    private final static QName _PackagingLevel_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "packagingLevel");
    private final static QName _FilesetPagination_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "filesetPagination");
    private final static QName _Total_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "total");
    private final static QName _ANVISARegistrationNumber_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "ANVISARegistrationNumber");
    private final static QName _CorrelationInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "CorrelationInformation");
    private final static QName _ScopeInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "ScopeInformation");
    private final static QName _PostRecoveryBatch_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "postRecoveryBatch");
    private final static QName _BusinessService_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "BusinessService");
    private final static QName _ReplacementEventID_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "replacementEventID");
    private final static QName _ExpirationDate_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "expirationDate");
    private final static QName _Reason_QNAME = new QName("http://epcis.gs1br.org/hc/ns", "reason");
    private final static QName _EPCISMasterDataDocument_QNAME = new QName("urn:epcglobal:epcis-masterdata:xsd:1", "EPCISMasterDataDocument");
    private final static QName _EventListTypeExtension_QNAME = new QName("", "extension");
    private final static QName _EventListTypeTransactionEvent_QNAME = new QName("", "TransactionEvent");
    private final static QName _EventListTypeObjectEvent_QNAME = new QName("", "ObjectEvent");
    private final static QName _EventListTypeQuantityEvent_QNAME = new QName("", "QuantityEvent");
    private final static QName _EventListTypeAggregationEvent_QNAME = new QName("", "AggregationEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.org.usp.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventListType }
     * 
     */
    public EventListType createEventListType() {
        return new EventListType();
    }

    /**
     * Create an instance of {@link EPCISDocumentType }
     * 
     */
    public EPCISDocumentType createEPCISDocumentType() {
        return new EPCISDocumentType();
    }

    /**
     * Create an instance of {@link EPCISHeaderExtensionType }
     * 
     */
    public EPCISHeaderExtensionType createEPCISHeaderExtensionType() {
        return new EPCISHeaderExtensionType();
    }

    /**
     * Create an instance of {@link SourceDestType }
     * 
     */
    public SourceDestType createSourceDestType() {
        return new SourceDestType();
    }

    /**
     * Create an instance of {@link BusinessTransactionType }
     * 
     */
    public BusinessTransactionType createBusinessTransactionType() {
        return new BusinessTransactionType();
    }

    /**
     * Create an instance of {@link TransactionEventExtensionType }
     * 
     */
    public TransactionEventExtensionType createTransactionEventExtensionType() {
        return new TransactionEventExtensionType();
    }

    /**
     * Create an instance of {@link EPCISEventListExtensionType }
     * 
     */
    public EPCISEventListExtensionType createEPCISEventListExtensionType() {
        return new EPCISEventListExtensionType();
    }

    /**
     * Create an instance of {@link ObjectEventExtension2Type }
     * 
     */
    public ObjectEventExtension2Type createObjectEventExtension2Type() {
        return new ObjectEventExtension2Type();
    }

    /**
     * Create an instance of {@link BusinessLocationExtensionType }
     * 
     */
    public BusinessLocationExtensionType createBusinessLocationExtensionType() {
        return new BusinessLocationExtensionType();
    }

    /**
     * Create an instance of {@link ILMDExtensionType }
     * 
     */
    public ILMDExtensionType createILMDExtensionType() {
        return new ILMDExtensionType();
    }

    /**
     * Create an instance of {@link EPCISEventListExtension2Type }
     * 
     */
    public EPCISEventListExtension2Type createEPCISEventListExtension2Type() {
        return new EPCISEventListExtension2Type();
    }

    /**
     * Create an instance of {@link SourceListType }
     * 
     */
    public SourceListType createSourceListType() {
        return new SourceListType();
    }

    /**
     * Create an instance of {@link QuantityEventType }
     * 
     */
    public QuantityEventType createQuantityEventType() {
        return new QuantityEventType();
    }

    /**
     * Create an instance of {@link EPCISDocumentExtensionType }
     * 
     */
    public EPCISDocumentExtensionType createEPCISDocumentExtensionType() {
        return new EPCISDocumentExtensionType();
    }

    /**
     * Create an instance of {@link QuantityEventExtensionType }
     * 
     */
    public QuantityEventExtensionType createQuantityEventExtensionType() {
        return new QuantityEventExtensionType();
    }

    /**
     * Create an instance of {@link ReadPointType }
     * 
     */
    public ReadPointType createReadPointType() {
        return new ReadPointType();
    }

    /**
     * Create an instance of {@link AggregationEventType }
     * 
     */
    public AggregationEventType createAggregationEventType() {
        return new AggregationEventType();
    }

    /**
     * Create an instance of {@link EPCISHeaderType }
     * 
     */
    public EPCISHeaderType createEPCISHeaderType() {
        return new EPCISHeaderType();
    }

    /**
     * Create an instance of {@link TransformationEventType }
     * 
     */
    public TransformationEventType createTransformationEventType() {
        return new TransformationEventType();
    }

    /**
     * Create an instance of {@link EPCISBodyType }
     * 
     */
    public EPCISBodyType createEPCISBodyType() {
        return new EPCISBodyType();
    }

    /**
     * Create an instance of {@link AggregationEventExtension2Type }
     * 
     */
    public AggregationEventExtension2Type createAggregationEventExtension2Type() {
        return new AggregationEventExtension2Type();
    }

    /**
     * Create an instance of {@link ILMDType }
     * 
     */
    public ILMDType createILMDType() {
        return new ILMDType();
    }

    /**
     * Create an instance of {@link EPCListType }
     * 
     */
    public EPCListType createEPCListType() {
        return new EPCListType();
    }

    /**
     * Create an instance of {@link DestinationListType }
     * 
     */
    public DestinationListType createDestinationListType() {
        return new DestinationListType();
    }

    /**
     * Create an instance of {@link ObjectEventExtensionType }
     * 
     */
    public ObjectEventExtensionType createObjectEventExtensionType() {
        return new ObjectEventExtensionType();
    }

    /**
     * Create an instance of {@link EPCISBodyExtensionType }
     * 
     */
    public EPCISBodyExtensionType createEPCISBodyExtensionType() {
        return new EPCISBodyExtensionType();
    }

    /**
     * Create an instance of {@link QuantityListType }
     * 
     */
    public QuantityListType createQuantityListType() {
        return new QuantityListType();
    }

    /**
     * Create an instance of {@link TransactionEventType }
     * 
     */
    public TransactionEventType createTransactionEventType() {
        return new TransactionEventType();
    }

    /**
     * Create an instance of {@link EPCISEventExtensionType }
     * 
     */
    public EPCISEventExtensionType createEPCISEventExtensionType() {
        return new EPCISEventExtensionType();
    }

    /**
     * Create an instance of {@link TransactionEventExtension2Type }
     * 
     */
    public TransactionEventExtension2Type createTransactionEventExtension2Type() {
        return new TransactionEventExtension2Type();
    }

    /**
     * Create an instance of {@link ReadPointExtensionType }
     * 
     */
    public ReadPointExtensionType createReadPointExtensionType() {
        return new ReadPointExtensionType();
    }

    /**
     * Create an instance of {@link ObjectEventType }
     * 
     */
    public ObjectEventType createObjectEventType() {
        return new ObjectEventType();
    }

    /**
     * Create an instance of {@link QuantityElementType }
     * 
     */
    public QuantityElementType createQuantityElementType() {
        return new QuantityElementType();
    }

    /**
     * Create an instance of {@link TransformationEventExtensionType }
     * 
     */
    public TransformationEventExtensionType createTransformationEventExtensionType() {
        return new TransformationEventExtensionType();
    }

    /**
     * Create an instance of {@link BusinessLocationType }
     * 
     */
    public BusinessLocationType createBusinessLocationType() {
        return new BusinessLocationType();
    }

    /**
     * Create an instance of {@link BusinessTransactionListType }
     * 
     */
    public BusinessTransactionListType createBusinessTransactionListType() {
        return new BusinessTransactionListType();
    }

    /**
     * Create an instance of {@link AggregationEventExtensionType }
     * 
     */
    public AggregationEventExtensionType createAggregationEventExtensionType() {
        return new AggregationEventExtensionType();
    }

    /**
     * Create an instance of {@link EPC }
     * 
     */
    public EPC createEPC() {
        return new EPC();
    }

    /**
     * Create an instance of {@link StandardBusinessDocumentHeader }
     * 
     */
    public StandardBusinessDocumentHeader createStandardBusinessDocumentHeader() {
        return new StandardBusinessDocumentHeader();
    }

    /**
     * Create an instance of {@link CorrelationInformation }
     * 
     */
    public CorrelationInformation createCorrelationInformation() {
        return new CorrelationInformation();
    }

    /**
     * Create an instance of {@link StandardBusinessDocument }
     * 
     */
    public StandardBusinessDocument createStandardBusinessDocument() {
        return new StandardBusinessDocument();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ManifestItem }
     * 
     */
    public ManifestItem createManifestItem() {
        return new ManifestItem();
    }

    /**
     * Create an instance of {@link ServiceTransaction }
     * 
     */
    public ServiceTransaction createServiceTransaction() {
        return new ServiceTransaction();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link DocumentIdentification }
     * 
     */
    public DocumentIdentification createDocumentIdentification() {
        return new DocumentIdentification();
    }

    /**
     * Create an instance of {@link PartnerIdentification }
     * 
     */
    public PartnerIdentification createPartnerIdentification() {
        return new PartnerIdentification();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link BusinessScope }
     * 
     */
    public BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link FilesetPaginationType }
     * 
     */
    public FilesetPaginationType createFilesetPaginationType() {
        return new FilesetPaginationType();
    }

    /**
     * Create an instance of {@link MasterDataType }
     * 
     */
    public MasterDataType createMasterDataType() {
        return new MasterDataType();
    }

    /**
     * Create an instance of {@link VocabularyListType }
     * 
     */
    public VocabularyListType createVocabularyListType() {
        return new VocabularyListType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataDocumentType }
     * 
     */
    public EPCISMasterDataDocumentType createEPCISMasterDataDocumentType() {
        return new EPCISMasterDataDocumentType();
    }

    /**
     * Create an instance of {@link VocabularyElementExtensionType }
     * 
     */
    public VocabularyElementExtensionType createVocabularyElementExtensionType() {
        return new VocabularyElementExtensionType();
    }

    /**
     * Create an instance of {@link IDListType }
     * 
     */
    public IDListType createIDListType() {
        return new IDListType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link VocabularyType }
     * 
     */
    public VocabularyType createVocabularyType() {
        return new VocabularyType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataBodyType }
     * 
     */
    public EPCISMasterDataBodyType createEPCISMasterDataBodyType() {
        return new EPCISMasterDataBodyType();
    }

    /**
     * Create an instance of {@link VocabularyElementListType }
     * 
     */
    public VocabularyElementListType createVocabularyElementListType() {
        return new VocabularyElementListType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataDocumentExtensionType }
     * 
     */
    public EPCISMasterDataDocumentExtensionType createEPCISMasterDataDocumentExtensionType() {
        return new EPCISMasterDataDocumentExtensionType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataHeaderExtensionType }
     * 
     */
    public EPCISMasterDataHeaderExtensionType createEPCISMasterDataHeaderExtensionType() {
        return new EPCISMasterDataHeaderExtensionType();
    }

    /**
     * Create an instance of {@link VocabularyElementType }
     * 
     */
    public VocabularyElementType createVocabularyElementType() {
        return new VocabularyElementType();
    }

    /**
     * Create an instance of {@link VocabularyExtensionType }
     * 
     */
    public VocabularyExtensionType createVocabularyExtensionType() {
        return new VocabularyExtensionType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataBodyExtensionType }
     * 
     */
    public EPCISMasterDataBodyExtensionType createEPCISMasterDataBodyExtensionType() {
        return new EPCISMasterDataBodyExtensionType();
    }

    /**
     * Create an instance of {@link EventListType.ObjectEvent }
     * 
     */
    public EventListType.ObjectEvent createEventListTypeObjectEvent() {
        return new EventListType.ObjectEvent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabularyListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:epcis-masterdata:xsd:1", name = "VocabularyList")
    public JAXBElement<VocabularyListType> createVocabularyList(VocabularyListType value) {
        return new JAXBElement<VocabularyListType>(_VocabularyList_QNAME, VocabularyListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "carrierParty")
    public JAXBElement<String> createCarrierParty(String value) {
        return new JAXBElement<String>(_CarrierParty_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "instance")
    public JAXBElement<BigInteger> createInstance(BigInteger value) {
        return new JAXBElement<BigInteger>(_Instance_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "filesetIdentifier")
    public JAXBElement<BigInteger> createFilesetIdentifier(BigInteger value) {
        return new JAXBElement<BigInteger>(_FilesetIdentifier_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:epcis:xsd:1", name = "EPCISDocument")
    public JAXBElement<EPCISDocumentType> createEPCISDocument(EPCISDocumentType value) {
        return new JAXBElement<EPCISDocumentType>(_EPCISDocument_QNAME, EPCISDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "manufacturingDate")
    public JAXBElement<XMLGregorianCalendar> createManufacturingDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ManufacturingDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "expectedNumUnits")
    public JAXBElement<BigInteger> createExpectedNumUnits(BigInteger value) {
        return new JAXBElement<BigInteger>(_ExpectedNumUnits_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "retractionFlag")
    public JAXBElement<Boolean> createRetractionFlag(Boolean value) {
        return new JAXBElement<Boolean>(_RetractionFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "eventID")
    public JAXBElement<String> createEventID(String value) {
        return new JAXBElement<String>(_EventID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocumentHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocumentHeader")
    public JAXBElement<StandardBusinessDocumentHeader> createStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
        return new JAXBElement<StandardBusinessDocumentHeader>(_StandardBusinessDocumentHeader_QNAME, StandardBusinessDocumentHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocument")
    public JAXBElement<StandardBusinessDocument> createStandardBusinessDocument(StandardBusinessDocument value) {
        return new JAXBElement<StandardBusinessDocument>(_StandardBusinessDocument_QNAME, StandardBusinessDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "retractionReason")
    public JAXBElement<String> createRetractionReason(String value) {
        return new JAXBElement<String>(_RetractionReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MovementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "natureOfMovement")
    public JAXBElement<MovementType> createNatureOfMovement(MovementType value) {
        return new JAXBElement<MovementType>(_NatureOfMovement_QNAME, MovementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "lotNumber")
    public JAXBElement<String> createLotNumber(String value) {
        return new JAXBElement<String>(_LotNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "declaringParty")
    public JAXBElement<String> createDeclaringParty(String value) {
        return new JAXBElement<String>(_DeclaringParty_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MasterDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "masterData")
    public JAXBElement<MasterDataType> createMasterData(MasterDataType value) {
        return new JAXBElement<MasterDataType>(_MasterData_QNAME, MasterDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackagingLevelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "expectedNumUnitUOM")
    public JAXBElement<PackagingLevelType> createExpectedNumUnitUOM(PackagingLevelType value) {
        return new JAXBElement<PackagingLevelType>(_ExpectedNumUnitUOM_QNAME, PackagingLevelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackagingLevelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "packagingLevel")
    public JAXBElement<PackagingLevelType> createPackagingLevel(PackagingLevelType value) {
        return new JAXBElement<PackagingLevelType>(_PackagingLevel_QNAME, PackagingLevelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilesetPaginationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "filesetPagination")
    public JAXBElement<FilesetPaginationType> createFilesetPagination(FilesetPaginationType value) {
        return new JAXBElement<FilesetPaginationType>(_FilesetPagination_QNAME, FilesetPaginationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "total")
    public JAXBElement<BigInteger> createTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_Total_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "ANVISARegistrationNumber")
    public JAXBElement<String> createANVISARegistrationNumber(String value) {
        return new JAXBElement<String>(_ANVISARegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "CorrelationInformation", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<CorrelationInformation> createCorrelationInformation(CorrelationInformation value) {
        return new JAXBElement<CorrelationInformation>(_CorrelationInformation_QNAME, CorrelationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "ScopeInformation")
    public JAXBElement<Object> createScopeInformation(Object value) {
        return new JAXBElement<Object>(_ScopeInformation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "postRecoveryBatch")
    public JAXBElement<String> createPostRecoveryBatch(String value) {
        return new JAXBElement<String>(_PostRecoveryBatch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "BusinessService", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<BusinessService> createBusinessService(BusinessService value) {
        return new JAXBElement<BusinessService>(_BusinessService_QNAME, BusinessService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "replacementEventID")
    public JAXBElement<String> createReplacementEventID(String value) {
        return new JAXBElement<String>(_ReplacementEventID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "expirationDate")
    public JAXBElement<XMLGregorianCalendar> createExpirationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ExpirationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://epcis.gs1br.org/hc/ns", name = "reason")
    public JAXBElement<String> createReason(String value) {
        return new JAXBElement<String>(_Reason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISMasterDataDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:epcis-masterdata:xsd:1", name = "EPCISMasterDataDocument")
    public JAXBElement<EPCISMasterDataDocumentType> createEPCISMasterDataDocument(EPCISMasterDataDocumentType value) {
        return new JAXBElement<EPCISMasterDataDocumentType>(_EPCISMasterDataDocument_QNAME, EPCISMasterDataDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISEventListExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extension", scope = EventListType.class)
    public JAXBElement<EPCISEventListExtensionType> createEventListTypeExtension(EPCISEventListExtensionType value) {
        return new JAXBElement<EPCISEventListExtensionType>(_EventListTypeExtension_QNAME, EPCISEventListExtensionType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionEvent", scope = EventListType.class)
    public JAXBElement<TransactionEventType> createEventListTypeTransactionEvent(TransactionEventType value) {
        return new JAXBElement<TransactionEventType>(_EventListTypeTransactionEvent_QNAME, TransactionEventType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventListType.ObjectEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ObjectEvent", scope = EventListType.class)
    public JAXBElement<EventListType.ObjectEvent> createEventListTypeObjectEvent(EventListType.ObjectEvent value) {
        return new JAXBElement<EventListType.ObjectEvent>(_EventListTypeObjectEvent_QNAME, EventListType.ObjectEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityEvent", scope = EventListType.class)
    public JAXBElement<QuantityEventType> createEventListTypeQuantityEvent(QuantityEventType value) {
        return new JAXBElement<QuantityEventType>(_EventListTypeQuantityEvent_QNAME, QuantityEventType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregationEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AggregationEvent", scope = EventListType.class)
    public JAXBElement<AggregationEventType> createEventListTypeAggregationEvent(AggregationEventType value) {
        return new JAXBElement<AggregationEventType>(_EventListTypeAggregationEvent_QNAME, AggregationEventType.class, EventListType.class, value);
    }

}
